[project]
name = "mills-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chess>=1.11.2",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
